config/routes.rb
Rails.application.routes.draw do

  get '/howToPlay', to: 'welcome#howTo'

  get '/socialhub', to: 'updates#index'

  get '/signup', to: 'admins#new'
  post '/signup',  to: 'admins#create'

  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'

  resources :updates
  resources :scores
  resources :admins


  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  before_save { email.downcase! }
  validates :adminName, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  validates :playerName, presence: true,
                    length: { minimum: 3 }
end

app/models/update.rb
class Update < ApplicationRecord

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show
    @admin = Admin.find(params[:id])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      log_in @admin
      redirect_to @admin

    else
      render 'new'
    end
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin.find(params[:id])
    if @admin.update_attributes(admin_params)
      redirect_to @admin
    else
      render 'edit'
    end
  end

  private

    def admin_params
      params.require(:admin).permit(:adminName, :email, :hby, :password,
                                   :password_confirmation)
    end

    def logged_in_admin
     unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url
     end
    end

    def correct_admin
      @admin = Admin.find(params[:id])
      redirect_to(root_url) unless current_admin?(@admin)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.all.sort_by {|s| s.score }.reverse.first(10)
    puts @scores
  end

  def show
      @score = Score.find(params[:id])
    end

  def new
    @score = Score.new
  end

  def create
    @score = Score.new(score_params)

    if @score.save
      redirect_to scores_path
    else
      render redirect_to scores_path
    end
  end

  private
  def score_params
    params.require(:score).permit(:playerName, :score)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by(email: params[:session][:email].downcase, hby: params[:session][:hby])
    if admin && admin.authenticate(params[:session][:password])
      log_in admin
      redirect_to admin
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
skip_before_action :verify_authenticity_token

  def index
      @updates = Update.all
  end

  def new
    @update = Update.new
  end

  def create
    @update = Update.new(update_params)
    if @update.save
      redirect_to @update
    else
      redirect_to '/socialhub'
    end
  end

  def show
    @update = Update.find(params[:id])
  end

  def edit
    @admin = current_admin
    @update = Update.find(params[:id])
  end

  def update
    @update = Update.find(params[:id])
    @update.update(edit_params)
    @update.save

    redirect_to @update
  end

  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    redirect_to updates_path
  end

  private
    def update_params
      params.require(:create).permit(:version, :description)
    end

    def edit_params
      params.require(:update).permit(:version, :description)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(admin)
    session[:admin_id] = admin.id
  end

  # Returns the current logged-in user (if any).
  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_admin.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:admin_id)
    @current_admin = nil
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin) do |f| %>

      <%= f.label :adminName %>
      <%= f.text_field :adminName, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :hby %>
      <%= f.text_field :hby, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'admins back', admin_path(current_admin)%>

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>This will be a signup page for new admins. Meaning it won't last long</p>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin, url: signup_path) do |f| %>

      <%= f.label :adminName %>
      <%= f.text_field :adminName, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :hby %>
      <%= f.text_field :hby, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admins/show.html.erb
<%= @admin.adminName %>, <%= @admin.email %>
<%= link_to "Settings", edit_admin_path(current_admin) %>
<%= link_to "All events", updates_path, class: "btn btn-lg btn-primary" %>

<%= link_to 'log out', logout_path(session), method: :delete, data: { confirm: 'Are you sure?' } %>

<form class="" action="/updates" enctype="multipart/form-data" method="post">
  <h3 id="">Create New Update</h3>
  <p id="">Version:</p>
  <input id="" type="text" name="[create]version">
  <p id="">Location</p>
  <input id="" type="text" name="[create]description">
  <input id="" type="submit" name="" value="submit">
</form>

<p id=""><a href ="/">HOME</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doc57</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Flavors|Mr+De+Haviland|VT323" rel="stylesheet">
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/scores/index.html.erb
<div id="leaderboard_div">
  <img src="assets/leaderboard.gif" width="1000px" height="525px">
  <h1 id="leaderboard_h1">Top Pilots</h1>

  <h3 id="player_h3">Player</h3>
  <h3 id="score_h3">Score</h3>
  <div id="rank_div">
    <h3 id="rank_h3">Rank</h3>
    <p>1st</p>
    <p>2nd</p>
    <p>3rd</p>
    <p>4th</p>
    <p>5th</p>
    <p>6th</p>
    <p>7th</p>
    <p>8th</p>
    <p>9th</p>
    <p>10th</p>
  </div>
  <div id="player_div">
    <table>
      <% @scores.each do |score| %>
        <tr>
          <td><p><%= score.playerName %></p></td>
          <td><p><%= score.score %></p></td>
        </tr>
      <% end %>
    </table>
  </div>
  <p id="menuLeaderboard_p" class="main_buttons"><a href="/">Main Menu</a></p>
</div>

app/views/scores/new.html.erb
<div id="gameArea_div">

	<div id="gameHeader_div">
		<img id="pic"src="/assets/topimage.jpg" width="1000px" height="200px">
		<h1 id="d" class="title">D</h1>
		<h1 id="oc" class="title">oc</h1>
		<h2 id="num" class="title">40</h2>
	  <p id=sub>cosmic marathon</p>
	  <h3 id=beta>beta</h3>
	</div>

	<div id="gameLeaderboards_div">
		<img src="/assets/leftSide.jpg" width="200px" height="360px">

		<div class="score">SCORE: <span id="score"></span></div>

	</div>

	<div id="gameStats_div">
		<img src="/assets/healthSide.jpg" width="200px" height="360px">
		<div id="screen">
		<div class="health"><div id="total"><div id="remaining"></div></div></div>
		<img id="heart"src="/assets/heart.png" width="35px" height="50px">

		<div id="score_form">
    	<%= form_with scope: :score, url: scores_path, local: true do |form| %>

    	<% if @score.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@score.errors.count, "error") %> prohibited
          this from being saved:
        </h2>
        <ul>
          <% @score.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <p id="text">
        <%= form.label :playerName %><br>
        <%= form.text_field :playerName %>
      </p>

      <p>
        <!--<input value= "score.innerHTML" type="text" name="score[score]" id="score_score">-->
        <%= form.label :playerName %><br>
        <%= form.hidden_field :score, :value => nil, id: 'hidden-score' %>

      </p>

      <p>
        <%= form.submit %>
      </p>

    <% end %>

    <%= link_to 'Back', root_path %>
    </div>
	</div>
	</div>

	<canvas id="background" width="600" height="360">
				Your browser does not support canvas. Please try again with a different browser.
	</canvas>
	<!-- The canvas for all enemy ships and bullets -->
	<canvas id="main" width="600" height="360"></canvas>

	<!-- The canvas the ship uses (can only move up one forth the screen.) -->
	<canvas id="ship" width="600" height="360"></canvas>


		<div class="game-over" id="game-over">GAME OVER<p><span onclick="game.restart()">Restart</span></p></div>
		<div id="loadingScreen">
			<p id="loading_p">LOADING...</p>
			<div id="loadingOutside"></div>
			<div id="loading"></div>
			<div id="objects">
				<p>Drawing Object:<p>
				<p id="do"class="loaded">loaded</p>
				<p>Ship Object:<p>
				<p id="so"class="loaded">loaded</p>
				<p>Game Object:<p>
				<p id="go"class="loaded">loaded</p>
				<p>Game Sound:<p>
				<p id="gs"class="loaded">loaded</p>
				<p>Sound Pool:<p>
				<p id="sp"class="loaded">loaded</p>
				<p>Bullet Pool:<p>
				<p id="bp"class="loaded">loaded</p>
			</div>
		</div>

    <script src="/assets/main.js"></script>
</div>

app/views/scores/show.html.erb
<p>
  <strong>Player Name:</strong>
  <%= @score.playerName %>
</p>

<p>
  <strong>score:</strong>
  <%= @score.score %>
</p>

app/views/updates/_form.html.erb
<%= form_with model: @update, local: true do |form| %>

  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@update.errors.count, "error") %> prohibited
        this update from being saved:
      </h2>
      <ul>
        <% @update.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :version %><br>
    <%= form.text_field :version %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/updates/edit.html.erb
<% if current_admin %>
<h1>Edit update</h1>


<%= form_with(model: @update, local: true) do |form| %>

  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@update.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @update.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :version %><br>
    <%= form.text_field :version %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>
<%= link_to 'admins back', admin_path(current_admin)%>

<% end %>

<p id=""><a href ="/">HOME</a></p>

app/views/updates/index.html.erb
<h1>Listing update</h1>

  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th></th>
    </tr>

    <% @updates.each do |update| %>
      <tr>
        <td><%= update.version %></td>
        <td><%= update.description %></td>
        <td><%= link_to 'Show', update_path(update) %></td>
        <td><%= link_to 'Edit', edit_update_path(update) %></td>
        <td><%= link_to 'Destroy', update_path(update),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

<% if current_admin %>
  <%= link_to 'admins back', admin_path(current_admin)%>
<% end %>

<p id=""><a href ="/">HOME</a></p>

app/views/updates/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<% end %>

app/views/updates/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @update.version %>
</p>

<p>
  <strong>Text:</strong>
  <%= @update.version %>
</p>

<% if current_admin %>
  <%= link_to 'admins back', admin_path(current_admin)%>
<% end %>

<p id=""><a href ="/">HOME</a></p>

app/views/welcome/howTo.html.erb
<div id="howTo_div">
  <div id="inner_div">

    <div id="enemies_div">
      <p id="enemies_p">Enemies</p>
      <img id="enemy_img" src="assets/enemy.png" width="25px" height="25px">
      <p id="enemy_p">20 points<p>
      <img id="elite_img" src="assets/elite.png" width="40px" height="40px">
      <p id="elite_p">50 points<p>
      <img id="titan_img" src="assets/titan.png" width="60px" height="60px">
      <p id="titan_p">125 points<p>
      <img id="goliath_img" src="assets/goliath.png" width="75px" height="75px">
      <p id="goliath_p">300 points<p>
    </div>

    <h1 id="d_h1" class="title">D</h1>
	  <h1 id="oc_h1" class="title">oc</h1>
	  <h2 id="num_h2" class="title">40</h2>

    <div id=instructions_div>
      <p>Move Ship Using Arrow Keys</p>
      <p>Destroy Enemies Using Spacebar</p>
      <p>When Enemies Wave Is Clear A New Wave WIll Spawn</p>
      <p>If Attacked By An Enemy Health Decreases</p>
      <p>Reaching Checkpoints Gives Health and other Bonuses</p>
      <p>Record The Highest Score To Be Doc 40's Top Pilot</p>
    </div>

  </div>
  <p id="menuHowTo_p" class="main_buttons"><a href="/">Main Menu</a></p>
</div>

app/views/welcome/index.html.erb
<script>
function sound()
{
  document.getElementById("welcome_audio").volume = 0.05;
}
</script>

<div id="main_div">
  <img src="assets/main_menu.jpg" onload="sound()" width="1000px" height="525px">
  <h1 id="d_h1" class="title">D</h1>
	<h1 id="oc_h1" class="title">oc</h1>
	<h2 id="num_h2" class="title">40</h2>
  <p id=subTitle_p>cosmic marathon</p>
  <h3 id=beta_h3>beta</h3>
  <div id="secondry_div">
    <p class="main_buttons"><a href="/scores/new">PLAY</a></p>
    <p class="main_buttons"><a href="/howToPlay">HOW TO PLAY</a></p>
    <p class="main_buttons"><a href="/scores">LEADERBOARDS</a></p>
    <p class="main_buttons"><a href="/socialhub">UPDATES</a></p>
    <% if current_admin %>
      <p class="main_buttons"><%= link_to 'admins back', admin_path(current_admin)%></p>
    <% else %>
      <p class="main_buttons"><a href="/login">ADMIN</a></p>
    <% end %>
  </div>
</div>
<audio id="welcome_audio" autoplay loop>
  <source src="assets/GladysKnight-LicencetoKill.mp3" type="audio/mpeg">
</audio>